import Testing

@testable import aoc_2025

@Suite("Day 07 Tests")
struct Day07Tests {

  let exampleInput = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

  @Test func part1() async throws {
    let result = Day07().part1(input: exampleInput)

    #expect(result == 21)
  }

  @Test func part2() async throws {
    let result = Day07().part2(input: exampleInput)

    #expect(result == 0)
  }
}
